spring:
  datasource:
    url: jdbc:mysql://${SPRING5_MYSQL_RECIPE_APP_MYSQ_DEV_HOST}:3306/sfg_dev
    username: ${SPRING5_MYSQL_RECIPE_APP_MYSQ_DEV_USER}
    password: ${SPRING5_MYSQL_RECIPE_APP_MYSQ_DEV_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true